baseURL = "https://placeos.com/"
languageCode = "en-us"
title = "PlaceOS"
theme = "til"
    
[params]
    title = "PlaceOS"
    subtitle = "Your platform for automating smart buildings."
    description = "Workplaces, campuses, and commercial real estate made smarter."
    dateFormat = "2006-01-02"
    showGraph = true
    customCSS = ["css/custom.css"]

[params.author]
    name = 'John Doe'

[params.products]
    pageSize = 20
    showCategoryFilter = true

[params.footer]
    creativeCommonsLicense = 'none'
    showCreativeCommonsIcons = false
    showThemeCredit = false


[outputs]
  home = ['html']
  section = ['html', 'rss', 'json']
  page = ['html']

[menus]
  [[menus.main]]
    name = 'Products'
    pageRef = '/products'
    weight = 20
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 30
  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 40

[markup]
  [markup.highlight]
    noClasses = false
    style = 'tokyonight-night'
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = false