baseURL = "https://placeos.com/"
languageCode = "en-us"
title = "PlaceOS"
theme = "til"
    
[params]
    title = "PlaceOS"
    subtitle = "The only open-source integration platform that retrofits commercial building systems – without ripping anything out"
    description = "Commercial buildings still run on disconnected systems – forcing IT, facilities, and space teams into manual workarounds and limiting the value of existing infrastructure. PlaceOS changes that by connecting your sensors, software & systems."
    dateFormat = "2006-01-02"
    showGraph = true
    customCSS = ["css/custom.css"]
    defaultImage = "static/PlaceOS.jpg"

[params.author]
    name = 'John Doe'

[params.products]
    pageSize = 20
    showCategoryFilter = true

[params.footer]
    creativeCommonsLicense = 'none'
    showCreativeCommonsIcons = false
    showThemeCredit = false


[outputs]
  home = ['html']
  section = ['html', 'rss', 'json']
  page = ['html']

[menus]
  [[menus.main]]
    name = 'workmate'
    pageRef = '/products/workmate'
    weight = 20
  [[menus.main]]
    name = 'stagehand'
    pageRef = '/products/stagehand'
    weight = 30
  [[menus.main]]
    name = 'lenspath'
    pageRef = '/products/lenspath'
    weight = 40

  [[menus.main]]
    name = 'backoffice'
    pageRef = '/products/backoffice'
    weight =50


[markup]
  [markup.highlight]
    noClasses = false
    style = 'tokyonight-night' 
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = false

[sitemap]
  filename = "sitemap.xml"
